In [2]:
import numpy as np
import laguide as lag
import scipy.linalg as sla

#Question 3a

A = np.array([
    [1, 2, -1],
    [2, 4, 0],
    [0, 1, -1],
])

#3b

A = np.array([
    [0, 1, 1],
    [1, -2, -1],
    [1, -1, 1],
])

#3c
A = np.array([
    [1, 1, -1, 0],
    [1, 1, 4, 3],
    [2, -1, 2, 4],
    [2, -1, 2, 3]
])

#3d
A = np.array([
    [0, 1, 1, 2],
    [0, 1, 1, -1],
    [1, 2, -1, 3],
    [1, 1, 2, 0]
])

'''
B = lag.RowAdd(B, 0, 3, -3)
L3 = lag.RowAdd(I, 0, 3, -3)


B = lag.RowSwap(B, 2, 3)
P2 = lag.RowSwap(I, 2, 3)
'''



'\nB = lag.RowAdd(B, 0, 3, -3)\nL3 = lag.RowAdd(I, 0, 3, -3)\n\n\nB = lag.RowSwap(B, 2, 3)\nP2 = lag.RowSwap(I, 2, 3)\n'

In [6]:
#3a
A = np.array([
    [1, 2, -1],
    [2, 4, 0],
    [0, 1, -1],
])

I = np.eye(3)

#Initial pivot elimination
A = lag.RowAdd(A, 0, 1, -2)
L1 = lag.RowAdd(I, 0, 1, -2)


#Row swapping is required. 
A = lag.RowSwap(A, 1, 2)
P1 = lag.RowSwap(I, 1, 2)

print(A)

#We now have a matrix that can be solved through back substitution.

print(P1)

[[ 1.  2. -1.]
 [ 0.  1. -1.]
 [ 0.  0.  2.]]
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [12]:
#3b
A = np.array([
    [0, 1, 1],
    [1, -2, -1],
    [1, -1, 1],
])

I = np.eye(3)

#Row swapping is required. 
A = lag.RowSwap(A, 0, 1)
P1 = lag.RowSwap(I, 0, 1)

#Pivot elimination
A = lag.RowAdd(A, 0, 2, -1)
L1 = lag.RowAdd(I, 0, 2, -1)


#Pivot elimination
A = lag.RowAdd(A, 1, 2, -1)
L1 = lag.RowAdd(I, 1, 2, -1)

print(A)

print(P1)

[[ 1. -2. -1.]
 [ 0.  1.  1.]
 [ 0.  0.  1.]]
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [18]:
#3c
A = np.array([
    [1, 1, -1, 0],
    [1, 1, 4, 3],
    [2, -1, 2, 4],
    [2, -1, 2, 3]
])

I = np.eye(4)

#Pivot elimination
A = lag.RowAdd(A, 0, 1, -1)
L1 = lag.RowAdd(I, 0, 1, -1)

A = lag.RowAdd(A, 0, 2, -2)
L2 = lag.RowAdd(I, 0, 2, -2)

A = lag.RowAdd(A, 0, 3, -2)
L3 = lag.RowAdd(I, 0, 3, -2)


#Row swapping required at this point
A = lag.RowSwap(A, 1, 2)
P1 = lag.RowSwap(I, 1, 2)


#Pivot elimination
A = lag.RowAdd(A, 1, 3, -1)
L4 = lag.RowAdd(I, 1, 3, -1)

print(A)

print(P1)

[[ 1.  1. -1.  0.]
 [ 0. -3.  4.  4.]
 [ 0.  0.  5.  3.]
 [ 0.  0.  0. -1.]]
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [27]:
#3d
A = np.array([
    [0, 1, 1, 2],
    [0, 1, 1, -1],
    [1, 2, -1, 3],
    [1, 1, 2, 0]
])

I = np.eye(4)

#Row swapping required at this point
A = lag.RowSwap(A, 0, 2)
P1 = lag.RowSwap(I, 0, 2)

#Pivot elimination
A = lag.RowAdd(A, 0, 3, -1)
L1 = lag.RowAdd(I, 0, 3, -1)

#Pivot elimination
A = lag.RowAdd(A, 1, 2, -1)
L2 = lag.RowAdd(I, 1, 2, -1)

#Pivot elimination
A = lag.RowAdd(A, 1, 3, 1)
L3 = lag.RowAdd(I, 1, 3, 1)

#Row swapping required at this point
A = lag.RowSwap(A, 2, 3)
P2 = lag.RowSwap(I, 2, 3)

print(A)

#Gauss-eliminated at this point. 
#Get P
print(P2 @ P1)

[[ 1.  2. -1.  3.]
 [ 0.  1.  1. -1.]
 [ 0.  0.  4. -4.]
 [ 0.  0.  0.  3.]]
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]
