In [1]:
#Round number to 3 digits. 

from math import floor, log10

import numpy as np

def R3(x):
    #Round a number to 3 digits

    return round(x, -int(floor(log10(abs(x)))) + (2))

In [2]:
def partial_pivot(A, n):

    # Iterate through each row in the matrix
    for i in range(n):
        pivot_row = i
        
        # Find the row with the maximum absolute value in the current column
        for j in range(i + 1, n):
            if abs(A[j][i]) > abs(A[pivot_row][i]):
                pivot_row = j
        
        # Swap the current row with the row having the maximum absolute value
        if pivot_row != i:
            A[[i, pivot_row]] = A[[pivot_row, i]]

        # Perform Gaussian elimination on the matrix
        
        #For everything below the pivot column, all the way to the last row:
        for j in range(i + 1, n):
            
            #Get factor and round factor
            factor = A[j][i] / A[i][i]
            factor = R3(factor)
            
            #Set entry below pivot to 0
            A[j][i] = 0
            
            #For each column following it:
            for k in range(i + 1, n + 1):
                #Get term: Factor * entry on pivot row
                subTerm = R3(factor * A[i][k])
                
                #Subtract and round
                A[j][k] -= subTerm
                A[j][k] = R3(A[j][k])
                
def back_substitute(A, n):
    
    #Slice matrix to get U, Y for back sub
    U = A[:,0:n]
    Y = A[:,n:]


    m = U.shape[0]  # m is number of rows and columns in U
    X = np.zeros((m,1))
    
    for i in range(m-1,-1,-1):  # Calculate entries backward from m-1 to 0
        X[i] = Y[i]
        for j in range(i+1,m):
            res = U[i][j]*X[j]
            X[i] -= R3(res[0])
            X[i] = R3(X[i][0]) #3 digit round
        if (U[i][i] != 0):
            X[i] /= R3(U[i][i])
            X[i] = R3(X[i][0]) #3 digit round
        else:
            print("Zero entry found in U pivot position",i,".")
    return X

In [3]:
A = np.array([
    [0.211, 0.811, 1.52],
    [1.71, - 1.06, -0.512]
])

partial_pivot(A, 2)
x = back_substitute(A, 2)
print(x)

[[0.743]
 [1.68 ]]


In [11]:
import numpy as np

def partial_pivot(A, n):

    # Iterate through each row in the matrix
    for i in range(n):
        pivot_row = i
        
        # Find the row with the maximum absolute value in the current column
        for j in range(i + 1, n):
            if abs(A[j][i]) > abs(A[pivot_row][i]):
                pivot_row = j
        
        # Swap the current row with the row having the maximum absolute value
        if pivot_row != i:
            A[[i, pivot_row]] = A[[pivot_row, i]]

        # Perform Gaussian elimination on the matrix
        
        #For everything below the pivot column, all the way to the last row:
        for j in range(i + 1, n):
            
            #Get factor and round factor
            factor = A[j][i] / A[i][i]
            
            #Set entry below pivot to 0
            A[j][i] = 0
            
            #For each column following it:
            for k in range(i + 1, n + 1):
                #Get term: Factor * entry on pivot row
                #Subtract
                A[j][k] -= factor * A[i][k]
                
def back_substitute(A, n):
    print(A)
    #Slice matrix to get U, Y for back sub
    U = A[:,0:n]
    Y = A[:,n:]

    print(U)
    print(Y)

    m = U.shape[0]  # m is number of rows and columns in U
    X = np.zeros((m,1))
    
    for i in range(m-1,-1,-1):  # Calculate entries backward from m-1 to 0
        X[i] = Y[i]
        for j in range(i+1,m):
            X[i] -= U[i][j]*X[j]
        if (U[i][i] != 0):
            X[i] /= U[i][i]
        else:
            print("Zero entry found in U pivot position",i,".")
    return X

In [13]:
A = np.array([
    [14.0, 15.0, 48.0],
    [21.0, -23.0, -2.0]
])

partial_pivot(A, 2)
x = back_substitute(A, 2)
print(x)

[[ 21.         -23.          -2.        ]
 [  0.          30.33333333  49.33333333]]
[[ 21.         -23.        ]
 [  0.          30.33333333]]
[[-2.        ]
 [49.33333333]]
[[1.68602826]
 [1.62637363]]
